[tools]
#awscli = "2"
#fzf = "latest"
#eza = "latest"
#zoxide = "latest"
#fd = "latest"
#ripgrep = "latest"
#bat = "latest"
#neovim = "v0.10.2"
jq = "latest"
yq = "latest"
#dasel = "latest"
#helm = "3"
#kubectl = "latest"
#kubectx = "latest"
#k9s = "latest"
#kind = "latest"
#pre-commit = "latest"
#lazygit = "latest"
#node = "22"
#pnpm = "latest"
#python = "3.13"
#pipx = "latest"
#uv = "latest"

#[alias]
#dasel = "https://github.com/asdf-community/asdf-dasel.git"

