[tools]
python = "3.11"
node = "20"
neovim = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
lazygit = "latest"
k9s = "latest"
eza = "latest"
zoxide = "latest"
starship = "latest"
xh = "latest"
