format = """
$username\
@\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$kubernetes\
$helm\
$aws\
$fill\
$cmd_duration $status\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "blue"
truncation_length = 4
truncate_to_repo = false

[username]
disabled = false
show_always = true
format = "[$user]($style)"

[hostname]
disabled = false
ssh_only = false
trim_at = "."
ssh_symbol = ""
format = "[$ssh_symbol$hostname]($style) "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[aws]
disabled = true
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "yellow"

[kubernetes]
disabled = false
style = "cyan"
format = '[$symbol$context( \($namespace\))]($style) '

[helm]
disabled = false
style = "white"
format = "[$symbol($version )]($style)"

[status]
success_symbol = ""
style = ""
format = '[\[$symbol$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
pipestatus = true

[cmd_duration]
disabled = false
style = "yellow"
format = "[$duration]($style)"

[memory_usage]
disabled = false
threshold = 1
format = "$symbol [${ram}]($style) "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"


